cmake_minimum_required(VERSION 3.8.2)
project(IOT_CORE_OSS
  VERSION ${IOT_CORE_OSS_VERSION}
  LANGUAGES C CXX
)

set(CMAKE_CXX_STANDARD 17)

# GStreamer plugin.
set(GST_QTI_C2_MODULE qtic2module)

add_library(${GST_QTI_C2_MODULE} SHARED
  c2-module.cc
)

set_target_properties(${GST_QTI_C2_MODULE} PROPERTIES PUBLIC_HEADER
  c2-module.h
)

target_compile_definitions(${GST_QTI_C2_MODULE} PRIVATE
  $<$<STREQUAL:${GST_CODEC2_CONFIG_VERSION},2.0>:CODEC2_CONFIG_VERSION_2_0>
  _LINUX_
)

target_link_libraries(${GST_QTI_C2_MODULE} PRIVATE
  codec2_vndk
)

install(
  TARGETS ${GST_QTI_C2_MODULE}
  LIBRARY DESTINATION ${IOT_CORE_OSS_INSTALL_LIBDIR}
  PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ
              GROUP_EXECUTE GROUP_READ
              WORLD_EXECUTE WORLD_READ
  PUBLIC_HEADER DESTINATION ${IOT_CORE_OSS_INSTALL_INCDIR}
)

